#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
02b_summary_tables.py
--------------------------
Post-sampling summary tables script. Must be run after 02_run_sampling.py.

Produces all summary tables and the Figure 5 input in one pass:

  Table 2    —  Population vs. excluded-ego attributes at nsample=500
  Table 3    —  (data generated by 04_boundary_conditions.py)
  Figure 5   —  summary_network_property_matchRP_combine_sample.csv
                (representativeness of RP vs. exclusion across all attributes)
  Figure 3A  —  % contaminated under 1st-degree criterion vs. sample size
  Figure 3B  —  % contaminated under 1st- + 2nd-degree criterion vs. sample size
  Figure 4A  —  % degree gap (post-exclusion vs. population), 1st-degree
  Figure 4B  —  % degree gap (post-exclusion vs. population), 1st+2nd-degree

Outputs (saved to output/tables/<network_version>/):
    summary_contamination_hop1_pcent.csv          (Figures 3A, 4A)
    summary_contamination_hop2_pcent.csv          (Figures 3B, 4B)
    table2_excluded_ego_attributes.csv            (Table 2, per network)
    summary_network_property_matchRP_combine_sample.csv  (Figure 5)

Combined outputs (saved to output/tables/):
    table2_population_vs_excluded.csv             (Table 2, all networks)

Usage
-----
    python scripts/02b_summary_tables.py
    python scripts/02b_summary_tables.py --network lastfm --nsim 20

Notes
-----
- Must be run after 01_prepare_networks.py and 02_run_sampling.py.
- Reads sampling outputs from --samples_dir (default: output/samples).
- Large networks (Twitch, Pokec): hop2 computed on-the-fly per node.
"""

import argparse
import os
import sys
import time

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from sampler import get_one_hop2_list, KS_dstat
from utils import NETWORK_CONFIG, SIMULATED_NETWORK_CONFIG, load_network_data

# ---------------------------------------------------------------------------
# Networks too large for pre-built hop2 list — compute on the fly
# ---------------------------------------------------------------------------
LARGE_NETWORKS = {"pokec", "twitch", "simulate_base"}

# Sample sizes to sweep (matching paper: 100 to 1000 in steps of 100)
SAMPLE_SIZES = list(range(100, 1001, 100))
NSIM         = 100


def contamination_one_sim(rd_node, hop1_list, hop2_list,
                           is_large, a_degree, pop_avg_degree):
    """
    For one simulation, compute contamination and post-exclusion stats
    under both 1st-degree and 1st+2nd-degree criteria.

    Contamination is defined as any ego with at least one sampled neighbor,
    regardless of condition (within or across). No need to split into
    treat/ctrl sets -- all ego-ego connections are contaminating.

    Parameters
    ----------
    rd_node : np.ndarray
        All 2*nsample sampled nodes (treat + ctrl combined).

    Returns dict with keys:
        ct1_pct, deg_clean1, pct_clean1, deg_diff1
        ct2_pct, deg_clean2, pct_clean2, deg_diff2
    """
    rd_set = set(rd_node)
    total  = len(rd_node)

    ct1 = set()
    ct2 = set()

    for ego in rd_node:
        h1 = hop1_list[ego] & rd_set
        if h1:
            ct1.add(ego)

        if is_large:
            h2 = get_one_hop2_list(ego, hop1_list)
        else:
            h2 = hop2_list[ego]
        if h1 or (h2 & rd_set):
            ct2.add(ego)

    clean1 = [n for n in rd_node if n not in ct1]
    clean2 = [n for n in rd_node if n not in ct2]

    def _safe_mean(arr, idx):
        return float(arr[idx].mean()) if len(idx) > 0 else np.nan

    deg1 = _safe_mean(a_degree, clean1)
    deg2 = _safe_mean(a_degree, clean2)

    return {
        "ct1_pct":    len(ct1) / total,
        "deg_clean1": deg1,
        "pct_clean1": len(clean1) / total,
        "deg_diff1":  (deg1 - pop_avg_degree) / pop_avg_degree if deg1 == deg1 else np.nan,
        "ct2_pct":    len(ct2) / total,
        "deg_clean2": deg2,
        "pct_clean2": len(clean2) / total,
        "deg_diff2":  (deg2 - pop_avg_degree) / pop_avg_degree if deg2 == deg2 else np.nan,
    }


def run_sweep(network_version, data_dir, output_dir, nsim, sample_sizes):
    """Run the full sweep for one network and save output CSVs."""
    print(f"\n{'='*60}\n  Contamination sweep: {network_version}\n{'='*60}")
    t0 = time.time()

    # Load data
    is_large           = network_version in LARGE_NETWORKS
    data               = load_network_data(network_version,
                                           load_hop2=(not is_large),
                                           data_dir=data_dir)
    a_degree           = data["a_degree"]
    a_cluster_coef     = data["a_cluster_coef"]
    a_eigen_centrality = data["a_eigen_centrality"]
    hop1_list          = data["hop1_list"]
    hop2_list          = data.get("hop2_list", None)

    total_node     = len(a_degree)
    pop_avg_degree = float(a_degree.mean())

    print(f"  N={total_node:,}, pop avg degree={pop_avg_degree:.3f}")
    print(f"  Large network (on-the-fly hop2): {is_large}")

    rows        = []
    table2_rows = []   # collect at nsample=500

    for nsample in sample_sizes:
        print(f"  Sample size {nsample}...", flush=True)
        sim_results = []

        for sim in range(nsim):
            rd_node = np.random.choice(total_node, nsample * 2, replace=False)

            res = contamination_one_sim(
                rd_node, hop1_list, hop2_list,
                is_large, a_degree, pop_avg_degree
            )
            sim_results.append(res)

        # Average across simulations
        avg = {k: float(np.nanmean([r[k] for r in sim_results]))
               for k in sim_results[0]}

        rows.append({
            "sample_size":          nsample,
            "pcent_contaminated_1": avg["ct1_pct"],
            "avg_degree_clean_1":   avg["deg_clean1"],
            "pcent_clean_1":        avg["pct_clean1"],
            "degree_diff_pct_1":    avg["deg_diff1"],
            "pcent_contaminated_2": avg["ct2_pct"],
            "avg_degree_clean_2":   avg["deg_clean2"],
            "pcent_clean_2":        avg["pct_clean2"],
            "degree_diff_pct_2":    avg["deg_diff2"],
            "pop_avg_degree":       pop_avg_degree,
        })
        print(f"    ct1={avg['ct1_pct']:.3f}  deg_diff1={avg['deg_diff1']:.3f}  "
              f"ct2={avg['ct2_pct']:.3f}  deg_diff2={avg['deg_diff2']:.3f}")

        # Table 2 data is collected in a separate pass below (nd_vec approach)

    # -----------------------------------------------------------------
    # Table 2: excluded ego attributes at nsample=500
    # Uses full contamination set (within ∪ across) = any ego with ≥1
    # sampled neighbor (nd_vec > 0), matching paper definition:
    # "no two sampled egos, within or across treatment conditions,
    # should be directly connected." Numerically equivalent to

    # -----------------------------------------------------------------
    import scipy.sparse as _sp
    _rows, _cols = [], []
    for _node, _nbs in hop1_list.items():
        for _nb in _nbs:
            _rows.append(_node); _cols.append(_nb)
    _A = _sp.csr_matrix((np.ones(len(_rows)), (_rows, _cols)),
                         shape=(total_node, total_node))

    TABLE2_NSAMPLE = 500
    TABLE2_NSIM    = 100
    t2_deg=[]; t2_clust=[]; t2_eigen=[]

    for sim in range(TABLE2_NSIM):
        np.random.seed(sim)
        rd = np.random.choice(total_node, TABLE2_NSAMPLE * 2, replace=False)
        d_vec = np.zeros(total_node); d_vec[rd] = 1
        nd_vec = _A.dot(d_vec)
        ct1 = rd[nd_vec[rd] > 0]          # all contaminated egos (within ∪ across)
        if len(ct1) > 0:
            t2_deg.append(float(a_degree[ct1].mean()))
            t2_clust.append(float(a_cluster_coef[ct1].mean()))
            t2_eigen.append(float(a_eigen_centrality[ct1].mean()))

    table2_rows += [
        {"network": network_version, "attribute": "degree",
         "population_mean": float(a_degree.mean()),
         "excluded_mean":   float(np.nanmean(t2_deg))},
        {"network": network_version, "attribute": "clustering",
         "population_mean": float(a_cluster_coef.mean()),
         "excluded_mean":   float(np.nanmean(t2_clust))},
        {"network": network_version, "attribute": "eigen_centrality",
         "population_mean": float(a_eigen_centrality.mean()),
         "excluded_mean":   float(np.nanmean(t2_eigen))},
    ]

    # Save
    df      = pd.DataFrame(rows)
    out_dir = os.path.join(output_dir, network_version)
    os.makedirs(out_dir, exist_ok=True)

    # Figures 3A + 4A (1st degree)
    hop1_df = df[["sample_size", "pcent_contaminated_1", "avg_degree_clean_1",
                  "pcent_clean_1", "degree_diff_pct_1", "pop_avg_degree"]]
    hop1_df.to_csv(os.path.join(out_dir, "summary_contamination_hop1_pcent.csv"),
                   index=False)

    # Figures 3B + 4B (1st + 2nd degree)
    hop2_df = df[["sample_size", "pcent_contaminated_2", "avg_degree_clean_2",
                  "pcent_clean_2", "degree_diff_pct_2", "pop_avg_degree"]]
    hop2_df.to_csv(os.path.join(out_dir, "summary_contamination_hop2_pcent.csv"),
                   index=False)

    # Table 2 (per-network)
    if table2_rows:
        pd.DataFrame(table2_rows).to_csv(
            os.path.join(out_dir, "table2_excluded_ego_attributes.csv"),
            index=False
        )

    elapsed = time.time() - t0
    print(f"  Saved to {out_dir}/")
    print(f"  Done in {elapsed/60:.1f} min")
    return df


def build_representativeness_table(
    network_version, a_degree, a_cluster_coef, a_eigen_centrality,
    a_nb_degree, num_initial_sample, nsim, samples_dir, output_dir
):
    """
    Build the representativeness comparison table (Figure 5 input).

    Reads the ego node files saved by 02_run_sampling.py and averages
    across nsim simulations. Outputs a 4-row table with columns:

        variable          — attribute name
        population_value  — population mean
        represent         — mean value in RP sample (avg over nsim sims)
        rp_vs_population  — mean KS(RP sample, population) over nsim sims
        remove            — mean value in post-exclusion sample
        rm_vs_population  — mean KS(exclusion sample, population)

    This format matches exactly what 06_figures.R expects for Figure 5.
    """
    rm_sim_dir = os.path.join(
        samples_dir, f"{network_version}_sample_{num_initial_sample}_remove"
    )
    rp_sim_dir = os.path.join(
        samples_dir, f"{network_version}_sample_match_{num_initial_sample}_ego_loss1"
    )

    rm_summary = pd.read_csv(
        os.path.join(rm_sim_dir, "summary_remaining_sample_size.csv")
    )
    rm_sizes = ((rm_summary["size g1"] + rm_summary["size g2"]) / 2).astype(int)

    attrs = {
        "degree":     a_degree,
        "clustering": a_cluster_coef,
        "eigen_c":    a_eigen_centrality,
        "nb_degree":  a_nb_degree,
    }

    rp_means = {k: [] for k in attrs}
    rp_ks    = {k: [] for k in attrs}
    rm_means = {k: [] for k in attrs}
    rm_ks    = {k: [] for k in attrs}

    for sim in range(nsim):
        nsample   = int(rm_sizes.iloc[sim])
        prefix_rm = os.path.join(rm_sim_dir, str(num_initial_sample))
        prefix_rp = os.path.join(rp_sim_dir, str(nsample))

        try:
            rm_node1 = np.genfromtxt(f"{prefix_rm}_ego_node1_sim{sim}.csv").astype(int)
            rm_node2 = np.genfromtxt(f"{prefix_rm}_ego_node2_sim{sim}.csv").astype(int)
            rp_node1 = np.genfromtxt(f"{prefix_rp}_ego_node1_sim{sim}.csv").astype(int)
            rp_node2 = np.genfromtxt(f"{prefix_rp}_ego_node2_sim{sim}.csv").astype(int)
        except OSError as e:
            print(f"    Warning: sim {sim} missing files ({e}), skipping.")
            continue

        rp_nodes = np.concatenate((rp_node1, rp_node2))
        rm_nodes = np.concatenate((rm_node1, rm_node2))

        for attr_name, arr in attrs.items():
            if len(rp_nodes) > 0:
                rp_means[attr_name].append(float(arr[rp_nodes].mean()))
                rp_ks[attr_name].append(float(KS_dstat(arr, arr[rp_nodes])))
            if len(rm_nodes) > 0:
                rm_means[attr_name].append(float(arr[rm_nodes].mean()))
                rm_ks[attr_name].append(float(KS_dstat(arr, arr[rm_nodes])))

    rows = []
    for attr_name, arr in attrs.items():
        rows.append({
            "variable":         attr_name,
            "population_value": float(arr.mean()),
            "represent":        float(np.nanmean(rp_means[attr_name])),
            "rp_vs_population": float(np.nanmean(rp_ks[attr_name])),
            "remove":           float(np.nanmean(rm_means[attr_name])),
            "rm_vs_population": float(np.nanmean(rm_ks[attr_name])),
        })

    result  = pd.DataFrame(rows)
    out_dir = os.path.join(output_dir, network_version)
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(
        out_dir, "summary_network_property_matchRP_combine_sample.csv"
    )
    result.to_csv(out_path, index=False)
    print(f"  Figure 5 table saved to {out_path}")
    return result


def main():
    all_networks = list(NETWORK_CONFIG.keys()) + list(SIMULATED_NETWORK_CONFIG.keys())

    parser = argparse.ArgumentParser(
        description="Post-sampling summary tables (Tables 2, Figures 3-5 data)."
    )
    parser.add_argument("--network",     nargs="+", default=["all"],
                        help="Network(s) to process, or 'all'.")
    parser.add_argument("--data_dir",    default="./data")
    parser.add_argument("--samples_dir", default="./output/samples",
                        help="Directory containing 02_run_sampling.py outputs.")
    parser.add_argument("--output_dir",  default="./output/tables")
    parser.add_argument("--nsim",        type=int, default=NSIM,
                        help=f"Simulations used in 02_run_sampling.py. Default: {NSIM}")
    parser.add_argument("--num_initial_sample", type=int, default=500,
                        help="Initial sample size used in 02_run_sampling.py. Default: 500")
    parser.add_argument("--seed",        type=int, default=0)
    args = parser.parse_args()

    np.random.seed(args.seed)
    os.makedirs(args.output_dir, exist_ok=True)

    network_labels = {
        "lastfm":                            "LastFM",
        "twitch":                          "Twitch",
        "pokec":                              "Pokec",
        "simulate_small":  "Small",
        "simulate_base":   "Base",
        "simulate_sparse":  "Sparse",
    }

    networks = all_networks if args.network == ["all"] else args.network
    table2_parts = []

    for nv in networks:
        print(f"\n{'='*60}\n  {nv}\n{'='*60}")

        # Load network attributes (needed for representativeness table)
        data = load_network_data(nv, load_hop2=False, data_dir=args.data_dir)
        a_degree           = data["a_degree"]
        a_cluster_coef     = data["a_cluster_coef"]
        a_eigen_centrality = data["a_eigen_centrality"]
        a_nb_degree        = data["a_nb_degree"]

        # -----------------------------------------------------------------
        # Part 1: Contamination sweep (Figures 3 & 4 + Table 2)
        # -----------------------------------------------------------------
        print("\n[Part 1] Contamination sweep (Figures 3 & 4, Table 2)...")
        run_sweep(nv, args.data_dir, args.output_dir, args.nsim, SAMPLE_SIZES)

        # Collect Table 2 rows for combined output
        fpath = os.path.join(args.output_dir, nv, "table2_excluded_ego_attributes.csv")
        if os.path.exists(fpath):
            df_t2 = pd.read_csv(fpath)
            df_t2["network"] = df_t2["network"].map(lambda x: network_labels.get(x, x))
            table2_parts.append(df_t2)

        # -----------------------------------------------------------------
        # Part 2: Representativeness table (Figure 5)
        # -----------------------------------------------------------------
        print("\n[Part 2] Building representativeness table (Figure 5)...")
        build_representativeness_table(
            nv, a_degree, a_cluster_coef, a_eigen_centrality, a_nb_degree,
            args.num_initial_sample, args.nsim,
            args.samples_dir, args.output_dir
        )

    # Combined Table 2 across all networks
    if table2_parts:
        table2 = pd.concat(table2_parts, ignore_index=True)
        out_path = os.path.join(args.output_dir, "table2_population_vs_excluded.csv")
        table2.to_csv(out_path, index=False)
        print(f"\nTable 2 (combined) saved to {out_path}")
        print(table2.pivot_table(
            index="attribute", columns="network",
            values=["population_mean", "excluded_mean"]
        ).round(4).to_string())

    print("\nAll networks complete.")


if __name__ == "__main__":
    main()
