#!/usr/bin/env Rscript
# =============================================================================
# 03_figures_34.R
# =============================================================================
# Generates Figures 3 and 4 from the paper.
#
# Figure 3: Contamination Rates by Sample Size Across Population Networks
#   Panel A — First-degree contamination rates
#   Panel B — First- and second-degree contamination rates
#
# Figure 4: Percentage Difference in Average Degree Between the Sample
#           and the Population
#   Panel A — Excluding first-degree contaminated egos
#   Panel B — Excluding first- and second-degree contaminated egos
#
# Input:
#   output/tables/<network>/summary_contamination_hop1_pcent.csv  (Fig 3A, 4A)
#   output/tables/<network>/summary_contamination_hop2_pcent.csv  (Fig 3B, 4B)
#   Generated by: scripts/02b_summary_tables.py
#
# Output (saved to output/figures/):
#   Figure3_contamination_rates.pdf
#   Figure3_contamination_rates.png
#   Figure4_degree_difference.pdf
#   Figure4_degree_difference.png
#
# Usage:
#   Rscript scripts/03_figures_34.R
#   or open in RStudio and source
#
# Required packages:
#   install.packages(c("tidyverse", "patchwork"))
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(patchwork)
})

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
if (interactive()) {
  # RStudio: set to repo root
  script_dir   <- dirname(rstudioapi::getSourceEditorContext()$path)
  root_dir     <- file.path(script_dir, "..")
} else {
  root_dir     <- "."
}
tables_dir  <- file.path(root_dir, "output", "tables")
figures_dir <- file.path(root_dir, "output", "figures")
dir.create(figures_dir, showWarnings = FALSE, recursive = TRUE)

# -----------------------------------------------------------------------------
# Networks and legend name mapping  (Excel name → paper name)
# -----------------------------------------------------------------------------
network_versions <- c(
  "lastfm",
  "twitch",
  "pokec",
  "simulate_small",
  "simulate_base",
  "simulate_sparse"
)

network_labels <- c(
  "lastfm"                            = "LastFM",
  "twitch"                          = "Twitch",
  "pokec"                              = "Pokec",
  "simulate_small"  = "Small",
  "simulate_base"   = "Base",
  "simulate_sparse"  = "Sparse"
)

# Order determines legend order — real networks first, then simulated
network_order <- c("LastFM", "Twitch", "Pokec", "Small", "Base", "Sparse")

# -----------------------------------------------------------------------------
# Color and line-type palette
# Distinguishable both in color and grayscale / black-and-white printing
# -----------------------------------------------------------------------------
network_colors <- c(
  "LastFM"  = "#1F4E79",
  "Twitch"  = "#2F6B3B",
  "Pokec"   = "#C00000",
  "Small"   = "#7A3B69",
  "Base"    = "#B07D2A",
  "Sparse"  = "#4A7C9E"
)

network_linetypes <- c(
  "LastFM"  = "solid",
  "Twitch"  = "dashed",
  "Pokec"   = "solid",
  "Small"   = "dotdash",
  "Base"    = "dotted",
  "Sparse"  = "longdash"
)

network_shapes <- c(
  "LastFM"  = 16,
  "Twitch"  = 17,
  "Pokec"   = 15,
  "Small"   = 18,
  "Base"    = 8,
  "Sparse"  = 4
)

# -----------------------------------------------------------------------------
# Shared theme (matches 06_figures.R style)
# -----------------------------------------------------------------------------
theme_fig34 <- function() {
  theme_minimal(base_size = 10) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor   = element_blank(),
      panel.grid.major.y = element_line(color = "grey82", linewidth = 0.3),
      panel.background   = element_rect(fill = "white", color = NA),
      plot.background    = element_rect(fill = "white", color = NA),
      axis.title.x       = element_text(size = 10),
      axis.title.y       = element_text(size = 10),
      axis.text.x        = element_text(size = 9),
      axis.text.y        = element_text(size = 9),
      plot.title         = element_text(size = 10.5, face = "plain"),
      legend.position    = "bottom",
      legend.box         = "horizontal",
      legend.key.width   = unit(2.2, "lines"),
      legend.key.height  = unit(0.9, "lines"),
      legend.text        = element_text(size = 9),
      legend.title       = element_blank(),
      legend.justification = "left",
      plot.margin        = margin(6, 8, 4, 6)
    )
}

# -----------------------------------------------------------------------------
# Load and combine data from all networks
# -----------------------------------------------------------------------------
load_sweep_data <- function(hop_suffix) {
  # hop_suffix: "hop1" or "hop2"
  map_dfr(network_versions, function(nv) {
    fpath <- file.path(tables_dir, nv,
                       paste0("summary_contamination_", hop_suffix, "_pcent.csv"))
    if (!file.exists(fpath)) {
      warning(paste("File not found:", fpath,
                    "\nRun scripts/02b_summary_tables.py first."))
      return(NULL)
    }
    df <- read.csv(fpath)
    df$network <- network_labels[nv]
    df
  })
}

data_hop1 <- load_sweep_data("hop1")
data_hop2 <- load_sweep_data("hop2")

if (nrow(data_hop1) == 0 || nrow(data_hop2) == 0) {
  stop(paste(
    "No data loaded. Run scripts/02b_summary_tables.py first to generate:\n",
    "  output/tables/<network>/summary_contamination_hop1_pcent.csv\n",
    "  output/tables/<network>/summary_contamination_hop2_pcent.csv"
  ))
}

# Factor with correct order
data_hop1$network <- factor(data_hop1$network, levels = network_order)
data_hop2$network <- factor(data_hop2$network, levels = network_order)

# Column name mapping: sweep script output → what we need
# hop1 file: pcent_contaminated_1, degree_diff_pct_1
# hop2 file: pcent_contaminated_2, degree_diff_pct_2
# Rename to unified names for plotting
data_hop1 <- data_hop1 %>%
  rename(pcent_contaminated = pcent_contaminated_1,
         degree_diff_pct    = degree_diff_pct_1)

data_hop2 <- data_hop2 %>%
  rename(pcent_contaminated = pcent_contaminated_2,
         degree_diff_pct    = degree_diff_pct_2)

# =============================================================================
# FIGURE 3 — Contamination Rates
# =============================================================================

make_contamination_panel <- function(df, panel_label, y_label = TRUE) {
  p <- ggplot(df, aes(x = sample_size, y = pcent_contaminated * 100,
                      color = network, linetype = network, shape = network)) +
    geom_line(linewidth = 0.75) +
    geom_point(size = 1.8) +
    scale_x_continuous(
      breaks = seq(100, 1000, 100),
      labels = seq(100, 1000, 100)
    ) +
    scale_y_continuous(
      labels = function(x) paste0(x, "%")
    ) +
    scale_color_manual(values = network_colors, breaks = network_order) +
    scale_linetype_manual(values = network_linetypes, breaks = network_order) +
    scale_shape_manual(values = network_shapes, breaks = network_order) +
    labs(
      title = panel_label,
      x     = "Sample Size",
      y     = if (y_label) "% Contaminated Egos" else NULL
    ) +
    theme_fig34() +
    guides(
      color    = guide_legend(nrow = 2),
      linetype = guide_legend(nrow = 2),
      shape    = guide_legend(nrow = 2)
    )
  return(p)
}

panel3a <- make_contamination_panel(data_hop1, "(A) First-Degree Contamination Rates",    y_label = TRUE)
panel3b <- make_contamination_panel(data_hop2, "(B) First- and Second-Degree Contamination Rates", y_label = FALSE)

figure3 <- panel3a + panel3b +
  plot_layout(ncol = 2, guides = "collect") &
  theme(legend.position = "bottom")

print(figure3)

ggsave(
  filename = file.path(figures_dir, "Figure3_contamination_rates.pdf"),
  plot     = figure3,
  width    = 8, height = 4.2, units = "in"
)
ggsave(
  filename = file.path(figures_dir, "Figure3_contamination_rates.png"),
  plot     = figure3,
  width    = 8, height = 4.2, units = "in", dpi = 300
)
cat("Figure 3 saved.\n")

# =============================================================================
# FIGURE 4 — Percentage Difference in Average Degree
# =============================================================================

make_degree_diff_panel <- function(df, panel_label, y_label = TRUE) {
  p <- ggplot(df, aes(x = sample_size, y = degree_diff_pct * 100,
                      color = network, linetype = network, shape = network)) +
    geom_hline(yintercept = 0, color = "grey60", linewidth = 0.4, linetype = "solid") +
    geom_line(linewidth = 0.75) +
    geom_point(size = 1.8) +
    scale_x_continuous(
      breaks = seq(100, 1000, 100),
      labels = seq(100, 1000, 100)
    ) +
    scale_y_continuous(
      labels = function(x) paste0(x, "%")
    ) +
    scale_color_manual(values = network_colors, breaks = network_order) +
    scale_linetype_manual(values = network_linetypes, breaks = network_order) +
    scale_shape_manual(values = network_shapes, breaks = network_order) +
    labs(
      title = panel_label,
      x     = "Sample Size",
      y     = if (y_label) "% Difference in Average Degree" else NULL
    ) +
    theme_fig34() +
    guides(
      color    = guide_legend(nrow = 2),
      linetype = guide_legend(nrow = 2),
      shape    = guide_legend(nrow = 2)
    )
  return(p)
}

panel4a <- make_degree_diff_panel(data_hop1, "(A) Excluding First-Degree Contaminated Egos",              y_label = TRUE)
panel4b <- make_degree_diff_panel(data_hop2, "(B) Excluding First- and Second-Degree Contaminated Egos",  y_label = FALSE)

figure4 <- panel4a + panel4b +
  plot_layout(ncol = 2, guides = "collect") &
  theme(legend.position = "bottom")

print(figure4)

ggsave(
  filename = file.path(figures_dir, "Figure4_degree_difference.pdf"),
  plot     = figure4,
  width    = 8, height = 4.2, units = "in"
)
ggsave(
  filename = file.path(figures_dir, "Figure4_degree_difference.png"),
  plot     = figure4,
  width    = 8, height = 4.2, units = "in", dpi = 300
)
cat("Figure 4 saved.\n")

cat("
All done. Output directory:", figures_dir, "
")
