#!/usr/bin/env Rscript
# 06_figures.R
# ------------
# Generates Figures 5, 6, and 7 from the paper.
# (Figures 3 and 4 are generated by scripts/03_figures_34.R)
#
# Inputs (from output/tables/<network_version>/):
#   summary_network_property_matchRP_combine_sample.csv  (Figure 5)
#   ate_sample500_tau1_0_0.1_tau2_0_sim100.csv          (Figure 6)
#   a_degree.csv                                         (Figure 6)
#
# Outputs (saved to output/figures/):
#   Figure5_representativeness.pdf
#   Figure6_ate.pdf
#   Figure7_cate.pdf
#
# Usage:
#   Rscript scripts/06_figures.R
#   Or open in RStudio and run interactively.
#
# Required packages: tidyverse, patchwork, grid, cowplot, ggbreak
# Install: install.packages(c("tidyverse","patchwork","cowplot","ggbreak"))

# Set working directory to output/tables where network subdirs live
output_tables <- file.path(dirname(rstudioapi::getSourceEditorContext()$path),
                           "..", "output", "tables")
if (!interactive()) {
  output_tables <- file.path("output", "tables")
}
output_figures <- file.path(dirname(output_tables), "figures")
dir.create(output_figures, showWarnings = FALSE, recursive = TRUE)

library(tidyverse)
library(patchwork)
library(grid)

# ---------------------------------------------------------
# Theme
# ---------------------------------------------------------
theme_mksc <- function() {
  theme_minimal(base_size = 10) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major.y = element_line(color = "grey82", linewidth = 0.3),
      axis.title.x = element_blank(),
      axis.title.y = element_text(size = 10),
      axis.text.x  = element_text(angle = 30, hjust = 1, size = 9),
      axis.text.y  = element_text(size = 9),
      plot.title   = element_text(size = 10.5, hjust = 0.3, face = "plain"),
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.key.width  = unit(2.2, "lines"),
      legend.key.height = unit(1.0, "lines"),
      legend.text  = element_text(size = 10),
      legend.title = element_text(size = 10),
      legend.justification = "left",
      legend.box.just = "left",
      plot.margin = margin(5, 5, 5, 5)
    )
}

# ---------------------------------------------------------
# File names and network names
# ---------------------------------------------------------
file_name <- "summary_network_property_matchRP_combine_sample.csv"

versions_ab <- c(
  "lastfm",
  "twitch",
  "pokec",
  "simulate_small",
  "simulate_base",
  "simulate_sparse"
)

group_names_ab <- c(
  "lastfm"                            = "LastFM",
  "twitch"                         = "Twitch",
  "pokec"                             = "Pokec",
  "simulate_small" = "Small",
  "simulate_base"  = "Base",
  "simulate_sparse" = "Sparse"
)

versions_c <- c(
  "simulate_small",
  "simulate_base",
  "simulate_sparse"
)

group_names_c <- c(
  "simulate_small" = "Small",
  "simulate_base"  = "Base",
  "simulate_sparse" = "Sparse"
)

# ---------------------------------------------------------
# Build data for Panels A and B
# ---------------------------------------------------------
combined_data_ab <- map_dfr(versions_ab, function(v) {
  file_path <- file.path(v, file_name)
  df <- read.csv(file_path)
  df$group <- group_names_ab[[v]]
  
  long_abs <- df %>%
    pivot_longer(
      cols = c("represent", "remove"),
      names_to = "version",
      values_to = "value"
    )
  
  long_ratio <- df %>%
    pivot_longer(
      cols = c("rp_vs_population", "rm_vs_population"),
      names_to = "version",
      values_to = "KS"
    ) %>%
    mutate(
      version = recode(
        version,
        "rp_vs_population" = "represent",
        "rm_vs_population" = "remove"
      )
    )
  
  left_join(
    long_abs,
    long_ratio,
    by = c("variable", "population_value", "group", "version")
  ) %>%
    select(variable, population_value, group, version, value, KS)
})

combined_data_ab <- combined_data_ab %>%
  mutate(
    version = recode(
      version,
      "represent" = "Representative",
      "remove"    = "Excluding"
    ),
    variable = factor(
      variable,
      levels = c("degree", "clustering", "eigen_c", "nb_degree"),
      labels = c(
        "Degree",
        "Clustering Coefficient",
        "Eigenvector Centrality",
        "Neighbor Degree"
      )
    ),
    group = factor(
      group,
      levels = c("LastFM", "Twitch", "Pokec", "Small", "Base", "Sparse")
    ),
    NetworkType = case_when(
      group %in% c("LastFM", "Twitch", "Pokec") ~ "Real-world",
      group %in% c("Small", "Base", "Sparse") ~ "Simulated"
    )
  )

# ---------------------------------------------------------
# Build data for Panel C
# ---------------------------------------------------------
combined_data_c <- map_dfr(versions_c, function(v) {
  file_path <- file.path(v, file_name)
  df <- read.csv(file_path)
  df <- df[df$variable %in% c("cov_z1", "cov_z2", "cov_z3"), ]
  df$group <- group_names_c[[v]]
  
  long_abs <- df %>%
    pivot_longer(
      cols = c("represent", "remove"),
      names_to = "version",
      values_to = "value"
    )
  
  long_ratio <- df %>%
    pivot_longer(
      cols = c("rp_vs_population", "rm_vs_population"),
      names_to = "version",
      values_to = "KS"
    ) %>%
    mutate(
      version = recode(
        version,
        "rp_vs_population" = "represent",
        "rm_vs_population" = "remove"
      )
    )
  
  left_join(
    long_abs,
    long_ratio,
    by = c("variable", "population_value", "group", "version")
  ) %>%
    select(variable, population_value, group, version, value, KS)
})

combined_data_c <- combined_data_c %>%
  mutate(
    version = recode(
      version,
      "represent" = "Representative",
      "remove"    = "Excluding"
    ),
    variable = factor(
      variable,
      levels = c("cov_z1", "cov_z2", "cov_z3"),
      labels = c("Z1", "Z2", "Z3")
    ),
    group = factor(
      group,
      levels = c("Small", "Base", "Sparse")
    ),
    NetworkType = "Simulated"
  )

# ---------------------------------------------------------
# Styles
# ---------------------------------------------------------
color_map <- c(
  "Real-world" = "#2F2F2F",
  "Simulated"  = "#7A8FA6"
)

linetype_map <- c(
  "Excluding"      = "22",
  "Representative" = "solid"
)

shape_map <- c(
  "Excluding"      = 17,
  "Representative" = 16
)

# ---------------------------------------------------------
# Plot functions
# ---------------------------------------------------------
plot_variable_ab <- function(df, var_name, title_text, show_legend = FALSE) {
  df_sub <- df %>% filter(variable == var_name)
  
  p <- ggplot(
    df_sub,
    aes(
      x = group,
      y = KS,
      color = NetworkType,
      linetype = version,
      shape = version,
      group = interaction(NetworkType, version)
    )
  ) +
    geom_line(linewidth = 0.7) +
    geom_point(size = 2.2) +
    scale_color_manual(
      values = color_map,
      drop = FALSE,
      name = "Network Type"
    ) +
    scale_linetype_manual(
      values = linetype_map,
      name = "Method"
    ) +
    scale_shape_manual(
      values = shape_map,
      guide = "none"
    ) +
    expand_limits(y = 0) +
    scale_y_continuous(limits = c(0, 0.25))+
    labs(
      title = title_text,
      y = "KS Distance"
    ) +
    guides(
      color = guide_legend(
        order = 1,
        override.aes = list(
          linetype = "solid",
          shape = NA,
          linewidth = 1.2
        )
      ),
      linetype = guide_legend(
        order = 2,
        override.aes = list(
          color = "black",
          linewidth = 1.2,
          linetype = c("22", "solid"),
          lineend = "butt"
        )
      )
    ) +
    theme_mksc()
  
  if (!show_legend) {
    p <- p + theme(legend.position = "none")
  }
  
  p
}

plot_variable_c <- function(df, var_name, title_text, show_legend = FALSE) {
  df_sub <- df %>% filter(variable == var_name)
  
  p <- ggplot(
    df_sub,
    aes(
      x = group,
      y = KS,
      linetype = version,
      shape = version,
      group = version
    )
  ) +
    geom_line(
      linewidth = 0.7,
      color = color_map["Simulated"]
    ) +
    geom_point(
      size = 2.2,
      color = color_map["Simulated"]
    ) +
    scale_linetype_manual(
      values = linetype_map,
      name = "Method"
    ) +
    scale_shape_manual(
      values = shape_map,
      guide = "none"
    ) +
    expand_limits(y = 0) +
    scale_y_continuous(limits = c(0, 0.06))+
    labs(
      title = title_text,
      y = "KS Distance"
    )  +
    guides(
      linetype = guide_legend(
        order = 2,
        override.aes = list(
          color = "black",
          linewidth = 1.2
        )
      )
    ) +
    theme_mksc()
  
  if (!show_legend) {
    p <- p + theme(legend.position = "none")
  }
  
  p
}

# ---------------------------------------------------------
# Create plots
# Only one plot keeps the legend
# ---------------------------------------------------------
p_degree   <- plot_variable_ab(combined_data_ab, "Degree", "Degree", show_legend = TRUE)
p_cluster  <- plot_variable_ab(combined_data_ab, "Clustering Coefficient", "Clustering Coefficient")
p_eigen    <- plot_variable_ab(combined_data_ab, "Eigenvector Centrality", "Eigenvector Centrality")
p_neighbor <- plot_variable_ab(combined_data_ab, "Neighbor Degree", "Neighbor Degree")

p_z1 <- plot_variable_c(combined_data_c, "Z1", "Z1")
p_z2 <- plot_variable_c(combined_data_c, "Z2", "Z2")
p_z3 <- plot_variable_c(combined_data_c, "Z3", "Z3")

# ---------------------------------------------------------
# Panel headers
# ---------------------------------------------------------
header_a <- ggplot() +
  annotate("text", x = 0.5, y = 0.1, label = "Panel A. Optimization Variables",
           size = 4) +
  theme_void()

header_b <- ggplot() +
  annotate("text", x = 0.5, y = 0.1, label = "Panel B. Network Variables",
            size = 4) +
  theme_void()

header_c <- ggplot() +
  annotate("text", x = 0.5, y = 0.1, label = "Panel C. Other Individual Variables",
          size = 4) +
  theme_void()

# ---------------------------------------------------------
# Assemble panels
# ---------------------------------------------------------
panel_a <- wrap_plots(
  A = header_a,
  B = p_degree,
  C = p_cluster,
  design = "
  AAAAAA
  BBBCCC
  ",
  heights = c(0.3, 1)
)

panel_b <- wrap_plots(
  A = header_b,
  B = p_eigen,
  C = p_neighbor,
  design = "
  AAAAAA
  BBBCCC
  ",
  heights = c(0.3, 1)
)

panel_c <- wrap_plots(
  A = header_c,
  B = p_z1,
  C = p_z2,
  D = p_z3,
  design = "
  AAAAAAAAA
  BBBCCCDDD
  ",
  heights = c(0.3, 1)
)

# ---------------------------------------------------------
# Final figure
# ---------------------------------------------------------
figure5 <- wrap_plots(
  panel_a,
  panel_b,
  panel_c,
  ncol = 1
) +
  plot_layout(guides = "collect", heights = c(1, 1, 1)) &
  theme(
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.justification = "left",
    legend.box.just = "left"
  )

figure5

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------
ggsave(
  file.path(output_figures, "Figure5_representativeness.pdf"),
  figure5,
  width = 7.5,
  height = 6.75,
  units = "in"
)


##############
###############
##############.  Figure 6


library(ggplot2)
library(cowplot)
library(dplyr)
library(patchwork)
library(ggbreak)
library(grid)

# ---------------------------------------------------------
# Working directory
# ---------------------------------------------------------
setwd("../output/tables")  # adjust if needed

# ---------------------------------------------------------
# Load data
# ---------------------------------------------------------
ate_table <- read.csv(file.path("simulate_base", "ate_sample500_tau1_0_0.1_tau2_0_sim100.csv"))
a_degree  <- read.csv(file.path("simulate_base", "a_degree.csv"), header = FALSE)

mean_degree <- mean(a_degree$V1)

# ---------------------------------------------------------
# Long estimator labels
# ---------------------------------------------------------
estimator_levels <- c(
  "Representative: Diff-in-Means",
  "Excluding: Diff-in-Means",
  "Excluding: Horvitz-Thompson",
  "Excluding: Hájek"
)

# ---------------------------------------------------------
# Prepare ADTE data
# ---------------------------------------------------------
adte_table <- ate_table %>%
  filter(estimator != "ols", tau2 == 0, estimand == "d10") %>%
  mutate(
    estimator = case_when(
      estimator == "diff-in-mean"     ~ "Excluding: Diff-in-Means",
      estimator == "Horvitz-Thompson" ~ "Excluding: Horvitz-Thompson",
      estimator == "Hajek"            ~ "Excluding: Hájek",
      estimator == "representative"   ~ "Representative: Diff-in-Means"
    ),
    power_percentage = power * 100,
    coverage_percentage = coverage * 100,
    Average_Treatment_Effect = tau1 * mean_degree
  )

adte_table$estimator <- factor(adte_table$estimator, levels = estimator_levels)

# ---------------------------------------------------------
# Prepare AITE data
# ---------------------------------------------------------
aite_table <- ate_table %>%
  filter(estimator != "ols", tau2 == 0, estimand == "d01") %>%
  mutate(
    estimator = case_when(
      estimator == "diff-in-mean"     ~ "Excluding: Diff-in-Means",
      estimator == "Horvitz-Thompson" ~ "Excluding: Horvitz-Thompson",
      estimator == "Hajek"            ~ "Excluding: Hájek",
      estimator == "representative"   ~ "Representative: Diff-in-Means"
    ),
    power_percentage = power * 100,
    coverage_percentage = coverage * 100,
    Average_Treatment_Effect = tau1 * mean_degree * 0.5
  )

aite_table$estimator <- factor(aite_table$estimator, levels = estimator_levels)

# ---------------------------------------------------------
# Aesthetics: color online, distinguishable in grayscale
# ---------------------------------------------------------
color_mapping <- c(
  "Representative: Diff-in-Means" = "#1F4E79",   # deep navy
  "Excluding: Diff-in-Means" = "#8B1E3F",        # dark red
  "Excluding: Horvitz-Thompson" = "#2F6B3B",    # dark green
  "Excluding: Hájek" = "#7A6F64"                # muted brown-gray
)

linetype_mapping <- c(
  "Representative: Diff-in-Means" = "solid",
  "Excluding: Diff-in-Means" = "44",
  "Excluding: Horvitz-Thompson" = "dotted",
  "Excluding: Hájek" = "dotdash"
)

shape_mapping <- c(
  "Representative: Diff-in-Means" = 16,
  "Excluding: Diff-in-Means" = 17,
  "Excluding: Horvitz-Thompson" = 15,
  "Excluding: Hájek" = 18
)

# ---------------------------------------------------------
# Theme
# ---------------------------------------------------------
theme_fig6 <- function() {
  theme_minimal(base_size = 10) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major.y = element_line(color = "grey92", linewidth = 0.25),
      panel.background = element_rect(fill = "white", color = NA),
      plot.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(size = 11, hjust = 0.5, face = "plain"),
      axis.title = element_text(size = 10),
      axis.text = element_text(size = 9),
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.key.width  = unit(3, "lines"),
      legend.key.height = unit(1.0, "lines"),
      legend.spacing.x  = unit(2, "cm"),
      legend.text = element_text(size = 8.5, margin = margin(r = 12)),
      legend.title = element_text(size = 9),
      plot.margin = margin(4, 4, 4, 4)
    )
}

# ---------------------------------------------------------
# Generic plotting function
# keep x-axis title only when requested
# ---------------------------------------------------------
plot_metric <- function(df, yvar, ylab, subtitle_text,
                        x_title = NULL,
                        show_legend = FALSE,
                        y_break = FALSE,
                        break_range = c(0.2, 1.0),
                        break_scale = 0.5) {
  
  present_levels <- estimator_levels[estimator_levels %in% unique(as.character(df$estimator))]
  
  p <- ggplot(
    df,
    aes(
      x = Average_Treatment_Effect,
      y = .data[[yvar]],
      color = estimator,
      linetype = estimator,
      shape = estimator,
      group = estimator
    )
  ) +
    geom_line(linewidth = 0.7) +
    geom_point(size = 2.0) +
    scale_color_manual(
      values = color_mapping,
      breaks = present_levels,
      limits = present_levels,
      name = "Estimator"
    ) +
    scale_linetype_manual(
      values = linetype_mapping,
      breaks = present_levels,
      limits = present_levels,
      name = "Estimator"
    ) +
    scale_shape_manual(
      values = shape_mapping,
      breaks = present_levels,
      limits = present_levels,
      name = "Estimator"
    ) +
    labs(
      x = x_title,
      y = ylab,
      title = subtitle_text
    ) +
    theme_fig6() +
    guides(
      color = guide_legend(
        order = 1,
        nrow = 2,
        byrow = TRUE,
        override.aes = list(
          linetype = unname(linetype_mapping[present_levels]),
          shape = unname(shape_mapping[present_levels]),
          linewidth = 0.9,
          size = 2.4
        )
      ),
      linetype = "none",
      shape = "none"
    )
  
  if (y_break) {
    p <- p + scale_y_break(break_range, scales = break_scale)
  }
  
  if (!show_legend) {
    p <- p + theme(legend.position = "none")
  }
  
  p
}
# ---------------------------------------------------------
# Panel A: ADTE
# ---------------------------------------------------------
adte_mae <- plot_metric(
  adte_table, "MAE", "Mean Absolute Error", "(A) Mean Absolute Error",
  x_title = NULL,
  show_legend = TRUE
)

adte_rmse <- plot_metric(
  adte_table, "rmse", "RMSE", "(B) RMSE",
  x_title = NULL
)

adte_power <- plot_metric(
  adte_table, "power_percentage", "Statistical Power (%)", "(C) Power",
  x_title = "Average Direct Treatment Effect"
)

adte_coverage <- plot_metric(
  adte_table, "coverage_percentage", "Coverage (%)", "(D) Coverage",
  x_title = "Average Direct Treatment Effect"
)

# ---------------------------------------------------------
# Panel B: AITE
# ---------------------------------------------------------
aite_mae <- plot_metric(
  aite_table, "MAE", "Mean Absolute Error", "(A) Mean Absolute Error",
  x_title = NULL,
  y_break = TRUE, break_range = c(0.2, 1.0), break_scale = 0.5
)

aite_rmse <- plot_metric(
  aite_table, "rmse", "RMSE", "(B) RMSE",
  x_title = NULL,
  y_break = TRUE, break_range = c(0.2, 1.0), break_scale = 0.5
)

aite_power <- plot_metric(
  aite_table, "power_percentage", "Statistical Power (%)", "(C) Power",
  x_title = "Average Indirect Treatment Effect"
)

aite_coverage <- plot_metric(
  aite_table, "coverage_percentage", "Coverage (%)", "(D) Coverage",
  x_title = "Average Indirect Treatment Effect"
)

# ---------------------------------------------------------
# Extract shared legend
# ---------------------------------------------------------
get_legend_only <- function(myplot) {
  tmp <- ggplotGrob(myplot + theme(legend.position = "bottom"))$grobs
  tmp[[which(sapply(tmp, function(x) x$name) == "guide-box")]]
}

shared_legend <- get_legend_only(adte_mae)

# ---------------------------------------------------------
# Build panel grids
# ---------------------------------------------------------
panel_a_grid <- plot_grid(
  adte_mae + theme(legend.position = "none"),
  adte_rmse + theme(legend.position = "none"),
  adte_power + theme(legend.position = "none"),
  adte_coverage + theme(legend.position = "none"),
  ncol = 2,
  align = "hv"
)

panel_b_grid <- plot_grid(
  aite_mae + theme(legend.position = "none"),
  aite_rmse + theme(legend.position = "none"),
  aite_power + theme(legend.position = "none"),
  aite_coverage + theme(legend.position = "none"),
  ncol = 2,
  align = "hv"
)

panel_a_header <- ggdraw() +
  draw_label("Panel A. Average Direct Treatment Effect", x = 0.5, y = 0.5, size = 12)

panel_b_header <- ggdraw() +
  draw_label("Panel B. Average Indirect Treatment Effect", x = 0.5, y = 0.5, size = 12)

panel_a <- plot_grid(
  panel_a_header,
  panel_a_grid,
  ncol = 1,
  rel_heights = c(0.1, 1)
)

panel_b <- plot_grid(
  panel_b_header,
  panel_b_grid,
  ncol = 1,
  rel_heights = c(0.1, 1)
)

# ---------------------------------------------------------
# Final figure
# ---------------------------------------------------------
spacer <- ggdraw()
figure6 <- plot_grid(
  panel_a,
  spacer,
  panel_b,
  shared_legend,
  ncol = 1,
  rel_heights = c(1,0.1, 1, 0.16)
)

print(figure6)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------
ggsave(
  filename = file.path("simulate_base", "Figure6_ADTE_AITE.pdf"),
  plot = figure6,
  width = 7,
  height = 8,
  units = "in",
  dpi = 600
)

ggsave(
  filename = file.path("simulate_base", "Figure6_ADTE_AITE.pdf"),
  plot = figure6,
  width = 7,
  height = 8.5,
  units = "in",
  dpi = 600
)

########
###########
###############. Figure 7

#################################################
##### Figure 7. Conditional ADTE Estimation Performance
library(tidyverse)
library(cowplot)
library(grid)

# ------------------------------------------------------------
# Data
# ------------------------------------------------------------
cadte_table <- tribble(
  ~degree_group, ~true_cadte, ~estimator, ~MAE, ~RMSE,
  
  "1–20",   0.660, "Excluding: Diff-in-Means",       0.140, 0.172,
  "1–20",   0.660, "Excluding: Horvitz-Thompson",    0.219, 0.261,
  "1–20",   0.660, "Excluding: Hájek",               0.141, 0.173,
  "1–20",   0.660, "Representative: Diff-in-Means",  0.108, 0.138,
  
  "21–50",  1.461, "Excluding: Diff-in-Means",       0.515, 0.627,
  "21–50",  1.461, "Excluding: Horvitz-Thompson",    0.960, 1.168,
  "21–50",  1.461, "Excluding: Hájek",               0.531, 0.653,
  "21–50",  1.461, "Representative: Diff-in-Means",  0.429, 0.542,
  
  "51–70",  2.936, "Excluding: Diff-in-Means",       4.079, 4.996,
  "51–70",  2.936, "Excluding: Horvitz-Thompson",    6.428, 7.866,
  "51–70",  2.936, "Excluding: Hájek",               4.134, 5.046,
  "51–70",  2.936, "Representative: Diff-in-Means",  2.635, 3.323,
  
  "71–100", 4.114, "Excluding: Diff-in-Means",       8.817, 10.761,
  "71–100", 4.114, "Excluding: Horvitz-Thompson",    13.567, 18.129,
  "71–100", 4.114, "Excluding: Hájek",               8.802, 10.784,
  "71–100", 4.114, "Representative: Diff-in-Means",  5.713, 6.927,
  
  ">100",   11.588, "Excluding: Diff-in-Means",      16.605, 21.177,
  ">100",   11.588, "Excluding: Horvitz-Thompson",   50.367, 78.735,
  ">100",   11.588, "Excluding: Hájek",              17.935, 22.429,
  ">100",   11.588, "Representative: Diff-in-Means", 13.245, 16.145
)

cadte_table$degree_group <- factor(
  cadte_table$degree_group,
  levels = c("1–20", "21–50", "51–70", "71–100", ">100")
)

estimator_levels <- c(
  "Representative: Diff-in-Means",
  "Excluding: Diff-in-Means",
  "Excluding: Horvitz-Thompson",
  "Excluding: Hájek"
)

cadte_table$estimator <- factor(cadte_table$estimator, levels = estimator_levels)

# ------------------------------------------------------------
# Same aesthetics as Figure 6
# ------------------------------------------------------------
color_mapping <- c(
  "Representative: Diff-in-Means" = "#1F4E79",   # deep navy
  "Excluding: Diff-in-Means" = "#8B1E3F",        # dark red
  "Excluding: Horvitz-Thompson" = "#2F6B3B",     # dark green
  "Excluding: Hájek" = "#7A6F64"                 # muted brown-gray
)

linetype_mapping <- c(
  "Representative: Diff-in-Means" = "solid",
  "Excluding: Diff-in-Means" = "44",
  "Excluding: Horvitz-Thompson" = "dotted",
  "Excluding: Hájek" = "dotdash"
)

shape_mapping <- c(
  "Representative: Diff-in-Means" = 16,
  "Excluding: Diff-in-Means" = 17,
  "Excluding: Horvitz-Thompson" = 15,
  "Excluding: Hájek" = 18
)

# ------------------------------------------------------------
# Theme
# ------------------------------------------------------------
theme_fig7 <- function() {
  theme_minimal(base_size = 10) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major.y = element_line(color = "grey92", linewidth = 0.25),
      panel.background = element_rect(fill = "white", color = NA),
      plot.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(size = 11, hjust = 0.5, face = "plain"),
      axis.title = element_text(size = 10),
      axis.text = element_text(size = 9),
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.key.width  = unit(3, "lines"),
      legend.key.height = unit(1.0, "lines"),
      legend.spacing.x  = unit(2, "cm"),
      legend.text = element_text(size = 8.5, margin = margin(r = 4)),
      legend.title = element_text(size = 9),
      plot.margin = margin(4, 4, 4, 4)
    )
}

# ------------------------------------------------------------
# Helper for shared legend
# ------------------------------------------------------------
get_legend <- function(myplot) {
  tmp <- ggplotGrob(myplot + theme(legend.position = "bottom"))$grobs
  tmp[[which(sapply(tmp, function(x) x$name) == "guide-box")]]
}

# ------------------------------------------------------------
# Generic plotting function
# ------------------------------------------------------------
plot_cadte_metric <- function(yvar, ylab, panel_title, show_legend = FALSE) {
  p <- ggplot(
    cadte_table,
    aes(
      x = degree_group,
      y = .data[[yvar]],
      color = estimator,
      linetype = estimator,
      shape = estimator,
      group = estimator
    )
  ) +
    geom_line(linewidth = 0.7) +
    geom_point(size = 2.0) +
    scale_color_manual(
      values = color_mapping,
      breaks = estimator_levels,
      name = "Estimator"
    ) +
    scale_linetype_manual(
      values = linetype_mapping,
      breaks = estimator_levels,
      name = "Estimator"
    ) +
    scale_shape_manual(
      values = shape_mapping,
      breaks = estimator_levels,
      name = "Estimator"
    ) +
    labs(
      x = "Degree Group",
      y = ylab,
      title = panel_title
    ) +
    theme_fig7() +
    guides(
      color = guide_legend(
        order = 1,
        nrow = 2,
        byrow = TRUE,
        override.aes = list(
          linetype = unname(linetype_mapping[estimator_levels]),
          shape = unname(shape_mapping[estimator_levels]),
          linewidth = 0.9,
          size = 2.4
        )
      ),
      linetype = "none",
      shape = "none"
    )
  
  if (!show_legend) {
    p <- p + theme(legend.position = "none")
  }
  
  p
}

# ------------------------------------------------------------
# Panel plots
# ------------------------------------------------------------
cadte_mae <- plot_cadte_metric(
  yvar = "MAE",
  ylab = "Mean Absolute Error",
  panel_title = "(A) Mean Absolute Error",
  show_legend = TRUE
)

cadte_rmse <- plot_cadte_metric(
  yvar = "RMSE",
  ylab = "Root Mean Squared Error",
  panel_title = "(B) Root Mean Squared Error",
  show_legend = FALSE
)

# ------------------------------------------------------------
# Shared legend
# ------------------------------------------------------------
shared_legend <- get_legend(cadte_mae)

# ------------------------------------------------------------
# Final Figure 7
# ------------------------------------------------------------

combined_plot <- plot_grid(
  cadte_mae + theme(legend.position = "none"),
  cadte_rmse + theme(legend.position = "none"),
  nrow = 1,
  align = "h"
)

figure7 <- plot_grid(
  combined_plot,
  shared_legend,
  ncol = 1,
  rel_heights = c(1, 0.2)
)



print(figure7)

# ------------------------------------------------------------
# Save PDF and PNG
# ------------------------------------------------------------
ggsave(
  filename = "Figure7_CADTE_performance.pdf",
  plot = figure7,
  width = 7,
  height = 2.5,
  units = "in"
)

ggsave(
  filename = "Figure7_CADTE_performance.png",
  plot = figure7,
  width = 7,
  height = 7.2,
  units = "in",
  dpi = 600
)

